server:
  port: 8888
  servlet:
    context-path: /community
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.141.60.249:3306/community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 8.141.60.249
    port: 6379
    database: 0
  thymeleaf:
    cache: false # 关闭缓存，方便测试
  mail: # Spring Mail的相关配置
    password: slemhreoetvlffab
    username: 1320959760@qq.com
    host: smtp.qq.com # 发件服务器
    port: 465
    protocol: smtps
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
community:
  path:
    domain: http://localhost:8888
    uploadPath: D:/log/upload/
